#! /usr/bin/env ruby

$: << 'test'
require 'bundler/setup'
require 'test_server'
require 'optparse'

options = {
  remote: false,
  sock: "test.sock"
}

OptionParser.new do |opts|
  opts.banner = "Usage: test_server [OPTIONS] [TEST...]"

  opts.on("--serve", "Boot the server") do |mode|
    options[:mode] = :serve
  end

  opts.on("--test", "Push a test to the server") do |mode|
    options[:mode] = :push
  end

  opts.on("--notify", "Send system notification based on test result") do |notify|
    options[:notify_on_fail] = notify
    options[:notify_on_pass] = notify
  end

  opts.on("--notify-on-pass", "Send system notification when the test passes") do |notify|
    options[:notify_on_pass] = notify
  end

  opts.on("--notify-on-fail", "Send system notification when the test fails") do |notify|
    options[:notify_on_fail] = notify
  end

  opts.on("--socket", "Socket file to use") do |sock|
    options[:sock] = sock
  end
end.parse!

options[:files] = ARGV
TestServer.run!(options)
