#! /usr/bin/env ruby

$: << 'test'
require 'test_server'
require 'optparse'

options = {
  remote: true,
  host: "localhost",
  port: 4545
}

OptionParser.new do |opts|
  opts.banner = "Usage: test_server_remote [OPTIONS] [TEST...]"

  opts.on("--serve", "Boot the server") do |mode|
    options[:mode] = :serve
  end

  opts.on("--test", "Push a test to the server") do |mode|
    options[:mode] = :push
  end

  opts.on("--notify", "Send system notification based on test result") do |notify|
    options[:notify_on_fail] = notify
    options[:notify_on_pass] = notify
  end

  opts.on("--notify-on-pass", "Send system notification when the test passes") do |notify|
    options[:notify_on_pass] = notify
  end

  opts.on("--notify-on-fail", "Send system notification when the test fails") do |notify|
    options[:notify_on_fail] = notify
  end

  opts.on("--port PORT", Integer, "Server's port (default: 4545)") do |port|
    options[:port] = port
  end

  opts.on("--host HOST", "Server's host (default: \"localhost\")") do |host|
    options[:host] = host
  end
end.parse!

options[:files] = ARGV
TestServer.run!(options)
